# Generated by Django 6.0.7 on 2026-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_department_student_address_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(blank=True, help_text='e.g. Tuition, Hostel, Exam', max_length=100),
        ),
    ]
